# Wildfly client for configuring another Wildfly server

FROM jboss/wildfly

MAINTAINER Lucas Russo

ADD customization /opt/jboss/wildfly/customization/
ADD modules /opt/jboss/wildfly/modules/

# User root user to install software
USER root

# Download JDBC connector
RUN OPTNAMESERVER
    curl -o /opt/jboss/wildfly/modules/org/postgres/main/postgresql-9.4.1207.jar https://jdbc.postgresql.org/download/postgresql-9.4.1207.jar

# Switch back to jboss user
USER jboss

RUN /opt/jboss/wildfly/customization/execute.sh
